### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by rblinzler** [rodi01/Artboard-Plus-XD#2]
Forgive me, I'm a bit out of practice with XD and plugins. After nearly a year hiatus I am back at it.
I can't find Artboard plus in the built-in XD Plugins manual and there is no included XD plugin install file (.xdx). 
How do I install?

**Comment by rodi01** [comment]
In XD go to the plugins menu -> Discover Plugins
You can search for Artboard Plus on that screen. 
![Screen Shot 2019-09-29 at 11 07 19 AM](https://user-images.githubusercontent.com/52461/65837206-71e9aa00-e2a9-11e9-915b-dea7523517c5.png)

**Comment by rblinzler** [comment]
Thank you for your very quick response. Followed your instructions and installed.
The first time, I simply gave up after typing 'artboard' when I didn't see it in the list..
Thank you for the plugin.
